all: heap_sort heap_sort_variant time_computations

heap_sort: heap_sort.cpp
	g++ -o heap_sort heap_sort.cpp
	./heap_sort

heap_sort_variant: heap_sort_variant.cpp
	g++ -o heap_sort_variant heap_sort_variant.cpp
	./heap_sort_variant

time_computations: time_computations.py
	python3 time_computations.py